### ISSUE TITLE
Work through haml-lint TODO

### ISSUE THREAD

**Issue by Riscky** [svsticky/constipated-koala#983]
We recently (#972) enabled haml-lint in order to get a grip on our messy haml.
Currently there are a lot of useful lints disabled because we have to work through their respective TODO's.
The TODO's can be found in `.haml-lint_todo.yml`.
The most important lints to enable are (imho):

- [ ] RepeatedId: It can be quite confusing to have multiple elements with the same id on the same page, and this breaks the assumptions of `getElementById`.
- [ ] LineLength: Current line lengths are quite bad, and often this is caused by having logic inside the view that should have been in the controller.
- [ ] RuboCop: Not all cops are as relevant, but the ruby in our haml templates is not consistent at all with our other ruby code. The linter also find potential security risks.
- [ ] InlineStyles: Although we should probably disable this for our mailers, we should not use inline styles anywhere else.

The other currently disabled linters seem less important

**Comment by Riscky** [comment]
We might want to wait for this PR https://github.com/sds/haml-lint/pull/346 to get merged before trying our hand at the RuboCop linters.
